# 应用名称
server:
  port: 8100

spring:
  application:
    name: spring-cloud-config-demo
  cloud:
    config:
      server:
        git:
          search-paths: config/{application}
          uri: https://github.com/IamMrChenH/spring-cloud-config-demo/